# Generated by Django 4.2 on 2023-04-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdeskapi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='softdeskapi.project'),
        ),
    ]
